name: change
version: 0.0.13
description: A Changelog manipulation library. Read/modify/write your CHANGELOG.md. Inspired by keepachangelog.com.
homepage: "https://github.com/f3ath/change"

dependencies:
  args: ^1.6.0
  intl: ^0.16.1
  markdown: ^2.0.2
  marker: ^0.1.0
  maybe_just_nothing: ^0.3.0
  pub_semver: ^1.4.4

dev_dependencies:
  pedantic: ^1.9.0
  pubspec_version: ^0.6.1
  test: ^1.9.0

environment:
  sdk: ">=2.8.0 <3.0.0"

executables:
  change: change
