name: change
description: A Changelog manipulation library. Read/modify/write your CHANGELOG.md. Inspired by keepachangelog.com.
version: 0.0.2
homepage: https://github.com/f3ath/change
author: "Alexey Karapetov <karapetov@gmail.com>"

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  markdown: ^2.0.2

dev_dependencies:
  test: ^1.0.0
