name: change
description: Changelog manipulation library. Read/modify/save your CHANGELOG.md.
# version: 1.0.0
# homepage: https://www.example.com
# author: karapeto <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  markdown: ^2.0.2
  intl: ^0.15.7

dev_dependencies:
  test: ^1.0.0
